# Default values for zkwasm-automata
replicaCount: 1

image:
  repository: ghcr.io/jupiterxiaoxiaoyu/zkwasm-automata
  pullPolicy: Always
  tag: "latest"  # Could be latest or MD5 value

# Mini-service configurations (deposit and settlement)
miniService:
  enabled: true
  image:
    repository: ghcr.io/jupiterxiaoxiaoyu/zkwasm-mini-service
    pullPolicy: Always
    tag: "latest"
  depositService:
    enabled: true
    replicaCount: 1
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
  settlementService:
    enabled: true
    replicaCount: 1
    resources:
      limits:
        cpu: 250m
        memory: 512Mi
      requests:
        cpu: 100m
        memory: 256Mi
  environment:
    image: ""
    settlementContractAddress: ""
    rpcProvider: ""
    chainId: 11155111

ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "8m"
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "180"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  tls:
    enabled: true
  domain:
    base: "zkwasm.ai"
    prefix: "rpc"  # Generate rpc.namespace.zkwasm.ai
  cors:
    enabled: true
    allowOrigins: "*"
    allowMethods: "GET, PUT, POST, DELETE, PATCH, OPTIONS"
    allowHeaders: "DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Authorization"
    allowCredentials: "true"
    maxAge: "1728000"

config:
  app:
    customEnv: {}
    deploy: "TRUE"
    remote: "TRUE"
    autoSubmit: ""
    migrate: "FALSE"
    image: ""
    migrateImageValue: ""
    settlementContractAddress: ""
    rpcProvider: ""
  mongodb:
    enabled: true
    image:
      repository: mongo
      tag: latest
    port: 27017
    resources:
      requests:
        memory: "512Mi"
        cpu: "200m"
      limits:
        memory: "1Gi"
        cpu: "500m"
    persistence:
      enabled: true
      storageClassName: csi-disk  
      size: 20Gi
  redis:
    enabled: true
    image:
      repository: redis
      tag: 7.4.2
    port: 6379
    resources:
      requests:
        memory: "1Gi"
        cpu: "150m"
      limits:
        memory: "1.5Gi"
        cpu: "300m"
  merkle:
    enabled: true
    image:
      repository: sinka2022/zkwasm-merkleservice
      tag: v1
    port: 3030

service:
  type: ClusterIP
  port: 3000

resources:
  limits:
    cpu: 1500m
    memory: 3Gi
  requests:
    cpu: 750m
    memory: 1.5Gi

# Mini-service secrets configuration
secrets:
  create: false
  name: "app-secrets"
  # These would be populated during installation
  # serverAdminKey: ""
  # settlerPrivateKey: ""

nodeSelector: {}
tolerations: []
affinity: {}
