{{- if and .Values.miniService.enabled .Values.miniService.depositService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zkwasm-automata.fullname" . }}-deposit
  labels:
    {{- include "zkwasm-automata.labels" . | nindent 4 }}
    app.kubernetes.io/component: deposit
spec:
  replicas: {{ .Values.miniService.depositService.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "zkwasm-automata.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: deposit
  template:
    metadata:
      labels:
        {{- include "zkwasm-automata.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: deposit
    spec:
      # 添加初始化容器检查 RPC 服务是否准备好
      initContainers:
      - name: wait-for-rpc
        image: busybox:1.28
        command: ['sh', '-c', 'for i in $(seq 1 30); do if nc -z {{ include "zkwasm-automata.rpcServiceName" . }} {{ .Values.service.port }}; then exit 0; fi; echo "Waiting for RPC ($i/30)"; sleep 10; done; exit 1']
      containers:
        - name: {{ .Chart.Name }}-deposit
          image: "{{ .Values.miniService.image.repository }}:{{ .Values.miniService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.miniService.image.pullPolicy }}
          # 使用文件系统或环境来检查进程，而不是ps命令
          startupProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "ls /proc/1 > /dev/null 2>&1 || echo 'Process check'"
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 30
          # 使用极其简单的就绪探针，延迟检查时间
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "echo 'Ready check'"
            initialDelaySeconds: 30
            periodSeconds: 20
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: DEPLOY
              value: "deposit"
            - name: MONGO_URI
              value: "mongodb://{{ include "zkwasm-automata.mongodbServiceName" . }}:{{ .Values.config.mongodb.port }}"
            - name: ZKWASM_RPC_URL
              value: "http://{{ include "zkwasm-automata.rpcServiceName" . }}:{{ .Values.service.port }}"
            - name: IMAGE
              value: "{{ .Values.miniService.environment.image | default .Values.config.app.image }}"
            - name: SETTLEMENT_CONTRACT_ADDRESS
              value: "{{ .Values.miniService.environment.settlementContractAddress | default .Values.config.app.settlementContractAddress }}"
            - name: RPC_PROVIDER
              value: "{{ .Values.miniService.environment.rpcProvider | default .Values.config.app.rpcProvider }}"
            - name: CHAIN_ID
              value: "{{ .Values.miniService.environment.chainId | default .Values.config.app.chainId | default "11155111" }}"
            {{- with .Values.config.app.customEnv }}
            {{- range $key, $val := . }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.miniService.depositService.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
