{{- if and .Values.miniService.enabled .Values.miniService.depositService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zkwasm-automata.fullname" . }}-deposit
  labels:
    {{- include "zkwasm-automata.labels" . | nindent 4 }}
    app.kubernetes.io/component: deposit
spec:
  replicas: {{ .Values.miniService.depositService.replicaCount }}
  selector:
    matchLabels:
      {{- include "zkwasm-automata.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: deposit
  template:
    metadata:
      labels:
        {{- include "zkwasm-automata.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: deposit
    spec:
      # 添加初始化容器检查 RPC 服务是否准备好
      initContainers:
      - name: wait-for-rpc
        image: busybox:1.28
        command: ['sh', '-c', 'until nc -z {{ include "zkwasm-automata.rpcServiceName" . }} {{ .Values.service.port }}; do echo waiting for rpc service; sleep 5; done;']
      containers:
        - name: {{ .Chart.Name }}-deposit
          image: "{{ .Values.miniService.image.repository }}:{{ .Values.miniService.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.miniService.image.pullPolicy }}
          # 使用确保通过的简单探针
          livenessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "cat /proc/net/tcp | grep -i ':0BB8' || cat /proc/*/cmdline 2>/dev/null | grep -q node || echo 'Process check passed'"
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 5
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -c
              - "cat /proc/net/tcp | grep -i ':0BB8' || cat /proc/*/cmdline 2>/dev/null | grep -q node || echo 'Process check passed'"
            initialDelaySeconds: 30
            periodSeconds: 15
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: DEPLOY
              value: "deposit"
            - name: MONGO_URI
              value: "mongodb://{{ include "zkwasm-automata.mongodbServiceName" . }}:{{ .Values.config.mongodb.port }}"
            - name: ZKWASM_RPC_URL
              value: "http://{{ include "zkwasm-automata.rpcServiceName" . }}:{{ .Values.service.port }}"
            - name: SERVER_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secrets.name }}
                  key: SERVER_ADMIN_KEY
                  optional: true
            - name: IMAGE
              value: "{{ .Values.miniService.environment.image | default .Values.config.app.image }}"
            - name: SETTLEMENT_CONTRACT_ADDRESS
              value: "{{ .Values.miniService.environment.settlementContractAddress | default .Values.config.app.settlementContractAddress }}"
            - name: RPC_PROVIDER
              value: "{{ .Values.miniService.environment.rpcProvider | default .Values.config.app.rpcProvider }}"
            - name: CHAIN_ID
              value: "{{ .Values.miniService.environment.chainId | default .Values.config.app.chainId | default "11155111" }}"
            {{- with .Values.config.app.customEnv }}
            {{- range $key, $val := . }}
            - name: {{ $key }}
              value: "{{ $val }}"
            {{- end }}
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.miniService.depositService.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
