apiVersion: v1
kind: Service
metadata:
  name: {{ include "zkwasm-automata.fullname" . }}-mongodb-headless
  labels:
    {{- include "zkwasm-automata.labels" . | nindent 4 }}
spec:
  clusterIP: None  # 这使其成为 Headless Service
  selector:
    app: {{ include "zkwasm-automata.fullname" . }}-mongodb
  ports:
  - port: {{ .Values.config.mongodb.port }}
    targetPort: {{ .Values.config.mongodb.port }}
    name: mongodb
