{{- if and .Values.config.mongodb.enabled .Values.config.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "zkwasm-automata.fullname" . }}-mongodb-pvc
  labels:
    {{- include "zkwasm-automata.labels" . | nindent 4 }}
    backup-enabled: "true"
    backup-type: "mongodb"
    app.kubernetes.io/component: "database"
    CCE-Cluster-Name: "mongodb-backup"
    app: "mongodb-database"
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.config.mongodb.persistence.size }}
  storageClassName: {{ .Values.config.mongodb.persistence.storageClassName }}
{{- end }}
