apiVersion: v1
kind: Service
metadata:
  name: {{ include "zkwasm-automata.fullname" . }}-rpc
  labels:
    {{- include "zkwasm-automata.labels" . | nindent 4 }}
    app.kubernetes.io/component: rpc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "zkwasm-automata.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: rpc
